/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.dbtext;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author m e s s
 */
public class textFileToTable extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    String projectPath = System.getProperty("user.dir").toString();
    int selectedRow;
    int kredit_total;
    int debit_total;
    int pendapatan_bersih;
    
    public textFileToTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        progressBar = new javax.swing.JProgressBar();
        loadFromDbBtn = new javax.swing.JButton();
        saveToDbBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addDataBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        addDescriptionTB = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        addDebitTB = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        addKreditTB = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        updateDataBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        updateDescriptionTB = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        updateDebitTB = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        updateKreditTB = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("MainFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Deskripsi", "Debit", "Kredit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataTable.setColumnSelectionAllowed(true);
        dataTable.getTableHeader().setReorderingAllowed(false);
        dataTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dataTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(dataTable);
        dataTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (dataTable.getColumnModel().getColumnCount() > 0) {
            dataTable.getColumnModel().getColumn(0).setResizable(false);
            dataTable.getColumnModel().getColumn(1).setResizable(false);
            dataTable.getColumnModel().getColumn(2).setResizable(false);
        }

        progressBar.setPreferredSize(new java.awt.Dimension(350, 15));

        loadFromDbBtn.setText("Load from DB");
        loadFromDbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFromDbBtnActionPerformed(evt);
            }
        });

        saveToDbBtn.setText("Save to DB");
        saveToDbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToDbBtnActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Data"));

        jLabel1.setText("Description");

        jLabel2.setText("Debit");

        jLabel3.setText("Kredit");

        addDataBtn.setText("Save");
        addDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataBtnActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(addDescriptionTB);

        jScrollPane3.setViewportView(addDebitTB);

        jScrollPane4.setViewportView(addKreditTB);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(13, 13, 13)
                .addComponent(addDataBtn)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Update Data"));

        jLabel4.setText("Description");

        jLabel5.setText("Debit");

        jLabel6.setText("Kredit");

        updateDataBtn.setText("Update");
        updateDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDataBtnActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(updateDescriptionTB);

        jScrollPane6.setViewportView(updateDebitTB);

        jScrollPane7.setViewportView(updateKreditTB);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6)
                            .addComponent(jScrollPane7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(updateDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(13, 13, 13)
                .addComponent(updateDataBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("Total :");

        totalLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(loadFromDbBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveToDbBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loadFromDbBtn)
                            .addComponent(saveToDbBtn))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    // Tombol Load from DB
    // Saat ditekan tombol Load from DB akan dilakukan blok program ini
    private void loadFromDbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFromDbBtnActionPerformed
        
        debit_total = 0;
        kredit_total = 0;
        
        // getModel() untuk menggunakan model dari table kita
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        
        // Untuk mengosongkan table sebelum di Load
        // Jika tidak dikosongkan maka akan duplikat
        model.setRowCount(0);
        
        // Path file kita akan sesuai dengan dimana projrct kita disimpan
        // projectPath ada di kelas utama sebagai konstanta
        String fileName = "data.txt";
        String filePath = projectPath + "\\" + fileName;
        File file = new File(filePath);
                
        try{
            BufferedReader br = new BufferedReader(new FileReader(file));
            Object[] tableLines = br.lines().toArray();
            for(int i = 0; i < tableLines.length; i++){
                // Ambil perbaris dari file text, masukkan satu persatu ke dalam table
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                model.addRow(dataRow);
                
                debit_total += Integer.parseInt(dataRow[1]);
                kredit_total += Integer.parseInt(dataRow[2]);
                
                // Untuk progress bar
                float progress = i * 100 / tableLines.length;
                System.out.println(progress);
                progressBar.setValue((int) progress);
            }
            
            pendapatan_bersih = debit_total - kredit_total;
            totalLabel.setText(String.valueOf(pendapatan_bersih));
        }
        catch(Exception ex){
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_loadFromDbBtnActionPerformed

    // Tombol save (untuk add data)
    // Bagian untuk memasukkan data baru
    private void addDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDataBtnActionPerformed
        // TODO add your handling code here:
        String description;
        String debit;
        String kredit;
        boolean add = true;
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        
        try{
            // isEmpty itu untuk ngecek, kosong atau engga form kita di app
            // kalo deskripsi kosong, gabisa add barang
            // kalo debit atau kredit kosong, bisa add barang, tapi auto jadi 0 kredit atau debitnya
            description = addDescriptionTB.getText().trim();
            if(description.isEmpty()){
                add = false;
                JOptionPane.showMessageDialog(null, "Isi Deskripsi!");
            }

            debit = addDebitTB.getText().trim();
            if(debit.isEmpty()){
                debit = "0";
            }

            kredit = addKreditTB.getText().trim();
            if(kredit.isEmpty()){
                kredit = "0";
            }
            
            if(add){
                model.addRow(new Object[]{description, debit, kredit});
            }
        }
        catch(HeadlessException ex){
            System.out.println(ex.toString());
        }        
    }//GEN-LAST:event_addDataBtnActionPerformed
    
    // Tombol save to DB
    // Bagian untuk save data di table kita ke dalam file text
    private void saveToDbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToDbBtnActionPerformed
        String fileName = "data.txt";
        String filePath = projectPath + "\\" + fileName;
        File file = new File(filePath);
        
        try{
            if(!file.exists()){
                file.createNewFile();
            }
            
            // File writer untuk membuat file 
            FileWriter fw = new FileWriter(file.getAbsoluteFile());
            
            // buffer writer ini buat temporary write sebelum di overwrite ke dalam txt nya
            BufferedWriter bw = new BufferedWriter(fw);

            for(int i = 0; i < dataTable.getRowCount(); i++){
                for(int j = 0; j < dataTable.getColumnCount(); j++){
                    bw.write(dataTable.getModel().getValueAt(i, j) + ",");
                }
                bw.write("\n");
            }
            bw.close();
            fw.close();
        }
        catch(IOException ex){
            System.out.println(ex.toString());
        }
        
    }//GEN-LAST:event_saveToDbBtnActionPerformed

    // Kalau ada bagian dari table yang di klik, otomatis terisi ke kotak bagian update
    private void dataTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataTableMousePressed
        // TODO add your handling code here:
        selectedRow = dataTable.rowAtPoint(evt.getPoint());
        int row = selectedRow;
        
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        
        String description = model.getValueAt(row, 0).toString();
        updateDescriptionTB.setText(description);
        
        String debit = model.getValueAt(row, 1).toString();
        updateDebitTB.setText(debit);
        
        String kredit = model.getValueAt(row, 2).toString();
        updateKreditTB.setText(kredit);
    }//GEN-LAST:event_dataTableMousePressed

    // kalau misal data yang udah ada di kotak update mau dimasukkan ke dalam table
    // maka bagian ini yang dijalankan
    private void updateDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDataBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) dataTable.getModel();
        String description = updateDescriptionTB.getText();
        String debit = updateDebitTB.getText();
        String kredit = updateKreditTB.getText();
        
        if(debit.isEmpty()){
            debit = "0";
        }

        if(kredit.isEmpty()){
            kredit = "0";
        }
        
        debit_total += Integer.parseInt(debit);
        kredit_total += Integer.parseInt(kredit);
        pendapatan_bersih = debit_total - kredit_total;
        totalLabel.setText(String.valueOf(pendapatan_bersih));
        
        model.setValueAt(description, selectedRow, 0);
        model.setValueAt(debit, selectedRow, 1);
        model.setValueAt(kredit, selectedRow, 2);
    }//GEN-LAST:event_updateDataBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(textFileToTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(textFileToTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(textFileToTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(textFileToTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new textFileToTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDataBtn;
    private javax.swing.JTextPane addDebitTB;
    private javax.swing.JTextPane addDescriptionTB;
    private javax.swing.JTextPane addKreditTB;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton loadFromDbBtn;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton saveToDbBtn;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JButton updateDataBtn;
    private javax.swing.JTextPane updateDebitTB;
    private javax.swing.JTextPane updateDescriptionTB;
    private javax.swing.JTextPane updateKreditTB;
    // End of variables declaration//GEN-END:variables
}
